apiVersion: apps/v1
kind: Deployment
metadata:
  name: orsb-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orsb-dev
  template:
    metadata:
      labels:
        app: orsb-dev
    spec:
      containers:
        - name: orsb-dev
          image: sh21202/orsb_dev:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
            - name: loglevel
              valueFrom:
                configMapKeyRef:
                  name: cm-ordev
                  key: loglevel
            - name: mysql-username
              valueFrom:
                secretKeyRef:
                  name: sc-ordev
                  key: loglevel
            - name: password
              valueFrom:
                configMapKeyRef:
                  name: cm-ordev
                  key: loglevel
                  - name: mysql-password
      imagePullSecrets:
        - name: sr-orsb-dev